// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingStock.Infrastructure.Context;

namespace TradingStock.Infrastructure.Migrations
{
    [DbContext(typeof(TradingStockDbContext))]
    [Migration("20181207193159_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TradingStock.Infrastructure.Model.Stock", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Down")
                        .HasColumnName("Down")
                        .HasColumnType("float");

                    b.Property<DateTime>("StockChange")
                        .HasColumnName("StockChange")
                        .HasColumnType("datetime");

                    b.Property<string>("StockType")
                        .HasColumnName("StockType")
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Up")
                        .HasColumnName("Up")
                        .HasColumnType("float");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 64)))
                        .HasColumnName("Version")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("TradingStock.Infrastructure.Model.StockEvent", b =>
                {
                    b.Property<Guid>("AggregateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("AggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnName("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .HasColumnName("EventType")
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnName("TimeStamp")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int>("Version")
                        .HasColumnName("Version")
                        .HasColumnType("int");

                    b.HasKey("AggregateId");

                    b.ToTable("StockEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
