// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingStock.Infrastructure.Context;

namespace TradingStock.Infrastructure.Migrations
{
    [DbContext(typeof(TradingStockDbContext))]
    partial class TradingStockDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TradingStock.Infrastructure.Model.Stock", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Down")
                        .HasColumnName("Down")
                        .HasColumnType("float");

                    b.Property<DateTime>("StockChange")
                        .HasColumnName("StockChange")
                        .HasColumnType("datetime");

                    b.Property<string>("StockType")
                        .HasColumnName("StockType")
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Up")
                        .HasColumnName("Up")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
